name = "BioSignals"
uuid = "b4c7f0a2-9ab6-42db-8e24-c5a5cb68647e"
authors = ["Michael Cassidy"]
version = "0.0.1"

[deps]
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"

[compat]
MAT = "0.10.7"
julia = "1.6.7"