name = "Wfdb"
uuid = "ab0b2baf-55f3-46e0-854a-b986eda60a22"
authors = ["Michael Cassidy"]
version = "1.0.0-DEV"

[deps]
Automa = "67c07d97-cdcb-5c2c-af73-a7f9c32a568b"

[compat]
Automa = "1.1.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
