name = "Wfdb"
uuid = "ab0b2baf-55f3-46e0-854a-b986eda60a22"
authors = ["Michael Cassidy"]
version = "1.0.0-DEV"

[deps]
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"

[compat]
MAT = "0.10.7"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
